resources:
- name: hello_world
  type: git
  source:
    uri: https://github.com/nimkha/hello_world.git
    branch: master

jobs:
- name: job-build-and-verify
  plan:
  - get: hello_world
    trigger: true
  - task: build-and-verify
    file: Hello_world/ci/mvn-build.yml