resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/nimkha/hello_world.git
      branch: master

jobs:
  - name: job-build-and-verify
    plan:
    - get: git-repo
      trigger: true
    - task: build-and-verify
      file: git-repo/ci/mvn-build.yml